name: Publish Container Image
on:
  workflow_dispatch:
    
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    name: publish-container-image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          
      - name: Build
        env:
          SNAPSHOT_TAG: ${{ github.ref_name }}
          KO_DOCKER_REPO: ${{ github.repository }}
        run: >
          make toolchain
          make build
